EOW #1
lyphrowny/IPlacer pull request #1
Opened 2022-09-17 19:59 UTC by lyphrowny

added:
- problem statement
- items' images
- test images of input data

2022-10-15 13:54 UTC, semen200251 commented on README.md
> +На выходе возвращается набор вмещенных предметов и отношение непокрытой площади многоугольника к площади всего многоугольника.
Не совсем понятно в каком виде программа выдаст набор вмещенных предметов.

2022-10-15 13:54 UTC, semen200251 commented on README.md
> +    1. Выделить лист, на котором расположен многоугольник
Не затруднит ли белый фон выделение белого листа на нём? Может ли программа воспринять резинку, которая не подходит по требованиям, за многоугольник из-за похожих цветов фона и листа?

2022-10-15 18:08 UTC, levs2001 requested changes
В целом, неплохо. 
Интересное усложнение с самопересечением многоугольника, я бы на такое не решился.

Из критичных замечаний: нужно добавить описание структуры данных, в которой будут храниться результаты выделения многоугольника и объектов. 
Также я бы задумался о вычислении размеров объектов заранее, поскольку их множество фиксированное.

2022-10-15 18:08 UTC, levs2001 commented on README.md
> -На вход подается изображение, на котором расположены заранее известные предметы и начерченный на белом листе бумаги многоугольник. Необходимо определить, поместятся ли все изображенные предметы в нач
В pull request не попал один из коммитов, видимо, самый первый.  В следующий раз будь аккуратнее, некоторые места не очень удобно комментить.

2022-10-15 18:08 UTC, levs2001 commented on README.md
> + * Расположен на белом листе A4 в центре
Эмм, предмет расположен на A4? Я посмотрел твои фото. Там предмет лежит на поверхности, а не на листе. И предмет на поверхности не единственный.
Пример:
<img width="1361" alt="image" src="https://user-images.githubusercontent.com/50678585/196000924-89c705a9-e656-40a6-a7d6-d30d914946d4.png">

2022-10-15 18:08 UTC, levs2001 commented on README.md
> +Необходимо расположить максимальное количество изображенных предметов в начерченный многоугольник. Если максимальное количество достигается с различным набором предметов, следует выбрать тот набор, н
У меня есть ощушение, что ты не ту задачу решаешь. Если почитать доку по Inteligent placer, там написано:
 "по поданной на вход фотографии нескольких предметов на светлой горизонтальной поверхности и многоугольнику понимать, можно ли расположить одновременно все эти предметы на плоскости так, чтобы они влезли в этот многоугольник."

А ты тут распологаешь максимальное количество предметов.

2022-10-15 18:08 UTC, levs2001 commented on README.md
> +        * Остальные предметы следует размещать так: самая длинная сторона объекта располагается по самой длинной стороне многоугольника вплотную, если это невозможно, делается параллельный перенос от
С каким шагом будешь поворачивать? Сколько раз будешь пытаться это сделать?
Например, будешь крутить на 10 градусов от 0 до 180.

2022-10-15 18:08 UTC, levs2001 commented on README.md
> +На выходе возвращается набор вмещенных предметов и отношение непокрытой площади многоугольника к площади всего многоугольника.
Если уж задаешь себе условие на то, чтобы в ответе было отношение покрытой к непокрытой, то и в примерах (размеченных данных) должно быть это.

2022-10-15 18:08 UTC, levs2001 commented on README.md
> + 4. Расположение объектов внутри многоугольника
Как будешь хранить размеры объекта и многоугольника? В виде массива вершин с координатами? В виде размеров площадей? Как?

2022-10-15 18:08 UTC, levs2001 commented on README.md
> +
Отлично, ты их выделил. Что вообще значит выделил, обвел в кружок? Закрасил розовым?)
Видимо, имеется в виду, запись результатов выделения в какую-ту структуру данных, с которой можно будет потом работать, добавь это описание.

2022-10-15 20:28 UTC, lyphrowny commented on README.md
> +Необходимо расположить максимальное количество изображенных предметов в начерченный многоугольник. Если максимальное количество достигается с различным набором предметов, следует выбрать тот набор, н
Решаемая задача -- усложнение базовой

2022-10-15 20:43 UTC, lyphrowny commented on README.md
> + * Расположен на белом листе A4 в центре
Нет, данное требование относится лишь к предметам исходных данных (один предмет на листе A4), не тестовых (совместное фото предметов с многоугольником). Требования к тестовым данных находятся [тут](https://github.com/lyphrowny/IPlacer/blob/develop/README.md#%D0%B8%D0%B7%D0%BE%D0%B1%D1%80%D0%B0%D0%B6%D0%B5%D0%BD%D0%B8%D1%8F-%D0%BF%D1%80%D0%B5%D0%B4%D0%BC%D0%B5%D1%82%D0%BE%D0%B2-%D1%81-%D0%BC%D0%BD%D0%BE%D0%B3%D0%BE%D1%83%D0%B3%D0%BE%D0%BB%D1%8C%D0%BD%D0%B8%D0%BA%D0%BE%D0%BC)

2022-10-15 20:51 UTC, lyphrowny commented on README.md
> +    1. Выделить лист, на котором расположен многоугольник
Скорее затруднит. Если предложенные методы поиска границ листа не будут успешны, будет либо заменен фон, либо более глубокое исследование методов, позволяющих выделить границы листа.

Добавлю пример тестовых данных с резинкой

- лежащей на пустом листе А5 на месте многоугольника (с \ без предметов)
- лежащей без листа на месте многоугольника (с \ без предметов)

2022-10-15 20:55 UTC, lyphrowny commented on README.md
> +
Для выделения предлагается использовать бинаризацию, поэтому выделенный объект = маска этого объекта.
Структуру добавлю, спасибо

2022-10-15 21:06 UTC, lyphrowny commented on README.md
> + 4. Расположение объектов внутри многоугольника
Скорее всего для предметов будет храниться несколько характеристик

- Пискельная площадь
- Максимальная длина (в пикселях) стороны прямоугольника, ограничивающего маску
- Величина шага перемещения
- Величина шага вращения

Поскольку многоугольник может самопересекаться, разделенные части многоугольника будут храниться в каком-то контейнере. Для каждого многоугольника будут храниться следующие характеристики

- Пиксельная площадь
- Контейнер с длинами ребер

Спасибо за предложение использовать координаты. Пока кажется, проще использовать пиксели

2022-10-15 21:14 UTC, lyphrowny commented on README.md
> +        * Остальные предметы следует размещать так: самая длинная сторона объекта располагается по самой длинной стороне многоугольника вплотную, если это невозможно, делается параллельный перенос от
Попробую учесть симметричность объектов: большинство не круглых в проекции объектов есть прямоугольники. Поскольку объекты располагаются длинной стороной к длинной строне многоугольника, вращать более чем на 90 градусов нецелесообразно. Предполагается вращать от -45 до 45 градусов. 

Кажется здравым сделать шаг вращения индивидуальным для каждого предмета: маленьким по площади - маленький шаг, большим - большой

2022-10-15 21:24 UTC, lyphrowny commented on README.md
> +На выходе возвращается набор вмещенных предметов и отношение непокрытой площади многоугольника к площади всего многоугольника.
Отношение площадей в размеченных данных отсутствует ввиду сложности вычисления на данном этапе. 
Убрать отношение из ответа тоже нельзя: будет непонятно, почему один набор предметов, а не другой.

Отношение будет добавлено после того, как программа сможет выделять многоугольник и предметы, чтобы вручную разместить полученные маски и посчитать отношение площадей. Заодно можно будет добавить пример возможного расположения предметов в многоугольнике.

2022-10-15 21:32 UTC, lyphrowny commented on README.md
> +На выходе возвращается набор вмещенных предметов и отношение непокрытой площади многоугольника к площади всего многоугольника.
Набор в виде строк-названий предметов.

Соответствие представленных предметов с предметами исходных данных будет, скорее всего, проверяться по площади (в пискелях) и по длине (в пикселях) наибольшей стороны прямоугольника, минимально описанного вокруг маски предмета. Возможно, потребуется переход к более разумным методам.

2022-10-21 21:33 UTC, magliy reviewed
Отревьюила код, ознакомьтесь с замечаниями

2022-10-21 21:33 UTC, magliy commented on README.md
> +Необходимо расположить максимальное количество изображенных предметов в начерченный многоугольник. Если максимальное количество достигается с различным набором предметов, следует выбрать тот набор, н
Стоит указать, что никакая часть предметов не выходит за границы многоугольника

2022-10-21 21:33 UTC, magliy commented on README.md
> +        * Края листа различимы на фоне, поэтому можно выделить углы листа, по которым возможно выделить весь лист
Можно указать, что поверхность, на фоне которой делаются фотографии светлая и ровная, без рельефа.

2022-10-27 04:07 UTC, lyphrowny commented on README.md
> +Необходимо расположить максимальное количество изображенных предметов в начерченный многоугольник. Если максимальное количество достигается с различным набором предметов, следует выбрать тот набор, н
Спасибо, добавлю

2022-10-27 04:07 UTC, lyphrowny commented on README.md
> +        * Края листа различимы на фоне, поэтому можно выделить углы листа, по которым возможно выделить весь лист
Добавлю

2022-10-27 04:07 UTC, merged